services:
  nodeapp:
    build: .
    ports:
      - "3003:3001"        # host:container (container listens on 3001)
    working_dir: /usr/src/mc_app
    command: npm start
    environment:
      - NODE_ENV=development

